# Default ALTS Benchmark Configuration
loops=5
project-id=directpath-security-manual
bucket=lwge-gcs-test-bucket
binaries=client_16kb,client_master,client_32kb
iterations=100
workers=1
object-size=2097152
write-buffer-size=-1
read-buffer-size=-1
test-download=false
transport=GRPC+DP
pprof-addr=
mem-stats=false
mem-monitor-interval=
